services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    command: ["sh", "-c", "npx prisma migrate deploy && node dist/server.js"]

  db:
    image: postgres:15
    container_name: vizgrc_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: vizgrc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: